services/infrastructure/RDS/serverless.yml
services/infrastructure/VPC/mainVPC/serverless.yml
services/infrastructure/VPC/subnet/serverless.yml

Serverless files to create a postgreSQL database with a VPC-network

Database and VPC  serverless.yml files done

---

services/ingestion/poller/YrPoller/serverless.yml
services/ingestion/poller/YrPoller/src/YrPoller/requirements.txt
services/ingestion/poller/YrPoller/src/YrPoller/yr_poller.py
templates/poller/src/function_1/fileName.py

Add poller for yr to dataplattform-v2
Am I doing this right?

#176/yr-poller

---

.github/workflows/lint.yaml

Denne vil legge til kommentar på koden som ikke er til standard for flake8(wrapperen som verifiserer pep8)

Add a linter for every pull request

---

services/ingestion/poller/YrPoller/serverless.yml
services/ingestion/poller/YrPoller/src/YrPoller/yr_poller.py
services/processing/YrProcessor/serverless.yml
services/processing/YrProcessor/src/Yr/requirements.txt
services/processing/YrProcessor/src/Yr/yr_hour.py
services/processing/YrProcessor/src/Yr/yr_processor.py

Make yr_processor to send the data from s3 to database.

Update yr_poller to send dicts, not lists.

---

services/ingestion/webHooks/googleForms/google_forms_webhook.py

Denne kollonen bør være en [boolean,](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.BooleanDtype.html) men fikk ikke dette til å fungere sammen med to_parquet.

Temporary fix of is_correct col type

---

packages/common/dataplattform/common/handlers/process.py
packages/common/tests/test_process_handler.py
packages/testing/dataplattform/testing/plugin.py
services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
services/ingestion/poller/cvPartner/serverless.yml
services/ingestion/poller/cvPartner/test_cv_partner_ingest_lambda.py
services/ingestion/poller/cvPartner/test_cv_partner_process_lambda.py

https://github.com/knowit/Dataplattform-issues/issues/252
https://github.com/knowit/Dataplattform-issues/issues/241
https://github.com/knowit/Dataplattform-issues/issues/251
https://github.com/knowit/Dataplattform-issues/issues/253
https://github.com/knowit/Dataplattform-issues/issues/250

Enhancements to cv_partner poller

---

services/fileStorageDistribution/.gitignore
services/fileStorageDistribution/jwtAuthenticator.py
services/fileStorageDistribution/package.json
services/fileStorageDistribution/preDeploy.py
services/fileStorageDistribution/requirements-test.txt
services/fileStorageDistribution/requirements.txt
services/fileStorageDistribution/serverless.yml
services/fileStorageDistribution/test_data/test_data.json
services/fileStorageDistribution/test_jwtAuthenticator.py
services/infrastructure/cognito/serverless.yml
services/infrastructure/storage/serverless.yml

Modifies cloudfront distribution to serve privat and public raw data

---

services/infrastructure/cognito/policies.js

update policies with access to reports table in dynamo and reports path in s3

Feature/user access for reports api 

---

services/infrastructure/datalake/serverless.yml

Krypterer alle nye objekter i s3

add default serverside encryption on datalake

---

packages/api/setup.py
packages/cli/setup.py
packages/common/setup.py
packages/query/setup.py
packages/testing/setup.py
services/api/fileStorageDistribution/requirements.txt
services/ingestion/cvPartner/requirements-test.txt
services/ingestion/cvPartner/requirements.txt
services/ingestion/gitHub/requirements.txt
services/ingestion/googleEvent/requirements-test.txt
services/ingestion/googleEvent/requirements.txt
services/ingestion/knowitLabs/requirements.txt
services/ingestion/slack/requirements.txt
services/ingestion/twitter/requirements.txt
services/ingestion/ubwFagtime/requirements.txt
services/ingestion/yrWeather/requirements.txt
templates/full_system/requirements.txt

Unpinna alt bortsett fra moto, pyathena og s3fs

unpin dependencies

---

.github/workflows/package-cli.yml
packages/cli/tests/requirements-test.txt
packages/common/dataplattform/common/aws.py
packages/testing/dataplattform/testing/plugin.py
services/api/dataApi/requirements-test.txt
services/ingestion/activeDirectory/active_directory_ingest_lambda.py
services/ingestion/activeDirectory/serverless.yml
services/ingestion/activeDirectory/test_active_directory_ingest_lambda.py

closes #knowit/Dataplattform-issues#377
Sletter alle entrys i tabellen før nye data blir lagt inn.

delete old ddb for ad before ingest

---

services/ingestion/activeDirectory/active_directory_ingest_lambda.py
services/ingestion/activeDirectory/test_active_directory_ingest_lambda.py

closes #knowit/dataplattform-issues#383

filter persons from ad data

---

services/ingestion/slack/package.json
services/ingestion/slack/requirements.txt
services/ingestion/slack/serverless.yml

Closes https://github.com/knowit/Dataplattform-issues/issues/321

Bumps dependency and increaces timer

---

.github/workflows/api-dataApi.yml
.github/workflows/api-fileDistribution.yml
.github/workflows/ingestion-activeDirectory.yml
.github/workflows/ingestion-cvPartner.yml
.github/workflows/ingestion-github.yml
.github/workflows/ingestion-googleEvent.yml
.github/workflows/ingestion-googleForms.yml
.github/workflows/ingestion-googleSheets.yml
.github/workflows/ingestion-jiraSales.yml
.github/workflows/ingestion-knowitLabs.yml
.github/workflows/ingestion-slack.yml
.github/workflows/ingestion-twitter.yml
.github/workflows/ingestion-ubwCustomerPerResource.yml
.github/workflows/ingestion-ubwFagtime.yml
.github/workflows/ingestion-yrWeather.yml
.github/workflows/package-api.yml
.github/workflows/package-cli.yml
.github/workflows/package-common.yml
.github/workflows/package-query.yml
.github/workflows/utils-downloadToBucket.yml

added 'develop' branch in push and pull for all files without prefix 'develop'.

added branch develop in push and pull workflows

---

services/infrastructure/vpc/serverless.yml

Reverts knowit/Dataplattform#218

Revert "Feature/configure vpc endpoint"

---

.github/workflows/api-dataApi.yml
.github/workflows/api-fileDistribution.yml
.github/workflows/ingestion-activeDirectory.yml
.github/workflows/ingestion-cvPartner.yml
.github/workflows/ingestion-github.yml
.github/workflows/ingestion-googleEvent.yml
.github/workflows/ingestion-googleForms.yml
.github/workflows/ingestion-googleSheets.yml
.github/workflows/ingestion-jiraSales.yml
.github/workflows/ingestion-knowitLabs.yml
.github/workflows/ingestion-slack.yml
.github/workflows/ingestion-twitter.yml
.github/workflows/ingestion-ubwCustomerPerResource.yml
.github/workflows/ingestion-ubwFagtime.yml
.github/workflows/ingestion-yrWeather.yml
.github/workflows/package-api.yml
.github/workflows/package-cli.yml
.github/workflows/package-common.yml
.github/workflows/package-query.yml
.github/workflows/utils-downloadToBucket.yml

Workflow runs on push only when applicable files are edited

---

services/api/dataApi/serverless.yml
services/api/documentation/postDeploy.py
services/api/documentation/serverless.yml
services/api/documentation/yarn.lock
services/api/fileStorageDistribution/serverless.yml
services/infrastructure/distribution/serverless.yml

- Added region to postdeploy.py.

- Switched out old ssm parameters to newer routes domain.

---

.github/workflows/deploy-ingestion-activeDirectoryProcess.yml
.github/workflows/deploy-ingestion-googleForms.yml
.github/workflows/deploy-ingestion-googleSheets.yml
.github/workflows/deploy-ingestion-slack.yml

Reverts knowit/Dataplattform#289

Revert "Fix/workflow deploy ingestion"

---

services/ingestion/twitter/serverless.yml
services/ingestion/twitter/twitter_ingest_lambda.py

set rate limit in ingest, up the duration before timeout

---

services/api/dataApi/requirements-test.txt
services/api/dataApi/requirements.txt
services/ingestion/ubwCustomerPerResource/lib/ubwcustomerperresource/ubw_customer_per_resource_process_lambda.py

added package and version to requirements.txt and fixed ubw_customer_per_resource_process_lambda to sort reg_periods correctly

Fixed failed tests for ubwCustomerPerResource and dataApi

---

services/api/documentation/package.json
services/api/documentation/webpack.config.js
services/api/documentation/yarn.lock

fixes dependabot alerts
- bumped webpack and plugins

bumped to webpack 5

---

.github/workflows/deploy-ingestion-slack.yml

added stage to register tables and update glue step in workflow for slack

changed slack workflow 

---

services/api/documentation/package.json
services/api/documentation/webpack.config.js
services/api/documentation/yarn.lock

fixes swagger not working after bumping to webpack 5
- added polyfills packages
- added webpack-dev-server
- ProvidePlugin sets the global value of Buffer to the Buffer export from buffer package

correctly configured webpack 5

---

services/ingestion/cvPartner/lib/cvpartner/cv_partner_process_lambda.py

fix bug with elem being None by added check for None

#631  added check for NoneType

---

services/ingestion/cvPartner/lib/cvpartner/cv_partner_process_lambda.py
services/ingestion/cvPartner/tests/test_cv_partner_process_lambda.py

to fix: https://github.com/knowit/Dataplattform-issues/issues/631
- added NoneType check for tag in elem is None
- added test for when tag is None

added test and check for when tag is None

---

services/api/documentation/package.json
services/api/documentation/yarn.lock

- Added resolutions for minimist and node-forge after dependabot alerts about these dependencies.
- bumped swagger-ui version as there was cross-site scripting in sanitize-url

Updated dependencies from dependabot alerts

---

.config/.serverless_monitoring
.github/workflows/deploy-infrastructure-monitoring.yml

Fikser https://github.com/knowit/Dataplattform/actions/runs/3042895162/jobs/4901560818

Deploy monitoring med serverless v 3.3.0

---

services/ingestion/ubwCustomerPerResource/serverless.yml

Bruk av && og || fungerer ikke som forventet, så jeg byttet til if else

Fiks postDeploy hook til ubwCustomerPerResource.

---

services/ingestion/ubwExperience/package.json

Endret feil navn i package.json

Changed bug in package.json

---

.github/workflows/deploy.yml

Reverts knowit/Dataplattform#500
Oppstod en feil med linje 90 i deploy.yml

Revert "Feature/461 slack notifications"

---

services/ingestion/activeDirectoryProcess/requirements.txt

#529 
Manglet numpy i requirements.txt

Add numpy to requirements.txt for activeDirectoryProcess

---

services/api/documentation/package.json
services/api/documentation/yarn.lock

Dependabot varsler om pakkeversjoner med sikkerhets hull, denne PR'en bumper pakker som fikser problemene

Bump packages to fix dependabot security warnings

---

services/ingestion/activeDirectory/serverless.yml

Increase ad timeout threshold

---

services/ingestion/activeDirectory/lib/activeDirectory/active_directory_ingest_lambda.py
services/ingestion/activeDirectory/tests/test_data/test_data_ingest.json

AD-data som ikke kommer inn siden feb. Har endret måten ingestor prøver å hente data på. AD har ikke det formatet på manager som tidligere kode antar, så må slå opp navn og epost.

Added lookup for manager and manager email

---

packages/cli/dataplattform/cli/commands/reports/requirements.txt
services/api/documentation/package.json
services/api/documentation/yarn.lock

First draft for report update/maintenance tool

Feature/458 lage scripts for å slette og opprette rapporter automatisk
